database:
  db_port: 3306
  db_username: "root"
  db_password: "password"
  name: "db_name"

github:
  github_token: ghp_xxx
  blacklist:
    - aaa
    - bbb

msf:
  #the folder used for git pull msf
  msf_dir: "/root/vul_info/msf/"

vulhub:
  #the folder used for git pull vulhub
  vulhub_dir: "/root/vul_info/vulhub/"

email:
  smtp_server: smtp.163.com
  smtp_port: 25
  username: test@163.com
  #授权码，不是邮箱密码
  password: xxxxxxxx
  from: test@163.com
  to:
    - test1@xxx.com
    - test2@xxx.com
