database:
  db_port: 3306
  db_username: "root"
  db_password: ""
  name: ""


#If downloadPOC is set to false, the poc_dir parameter in GitHub, ExploitDB, and PacketStorm does not need to be configured
poc:
  downloadPOC: false							#whether to download poc

github:
  github_token: ghp_xxx
  poc_dir: "/root/vul_info/poc/github/"			#dir for GitHub PoCs
  blacklist:									#github blacklist users
    - xxx
    - aaa

exploitdb:
  poc_dir: "/root/vul_info/poc/exploitdb/"		#dir for exploit-db PoCs

packetstorm:
  poc_dir: "/root/vul_info/poc/packetstorm/"	#dir for packetstorm PoCs

email:
  smtp_server: smtp.163.com
  smtp_port: 25
  username: test@163.com
  password: xxx									#authentication code
  from: test@163.com
  to:
    - test1@163.com
    - test2@163.com
